# Generated by Django 5.2.7 on 2025-10-29 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movielist_app', '0002_collectionlist_streamplatform_delete_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionlist',
            name='platform',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='collectionlist', to='movielist_app.streamplatform'),
            preserve_default=False,
        ),
    ]
